version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: MundialCorporativo.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=mundial_corporativo;Username=postgres;Password=postgres

  db:
    image: postgres:15
    container_name: mundial_corporativo_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mundial_corporativo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
