// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MundialCorporativo.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MundialCorporativo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MundialCorporativo.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AwayPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HomePoints")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MatchDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            AwayScore = 1,
                            AwayTeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            HomeScore = 2,
                            HomeTeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MatchDateUtc = new DateTime(2026, 2, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            AwayScore = 0,
                            AwayTeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            HomeScore = 0,
                            HomeTeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MatchDateUtc = new DateTime(2026, 2, 24, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            AwayScore = 3,
                            AwayTeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            HomeScore = 1,
                            HomeTeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MatchDateUtc = new DateTime(2026, 2, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            AwayTeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            HomeTeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MatchDateUtc = new DateTime(2026, 3, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            AwayTeamId = new Guid("44444444-4444-4444-4444-444444444444"),
                            HomeTeamId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MatchDateUtc = new DateTime(2026, 3, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            AwayTeamId = new Guid("33333333-3333-3333-3333-333333333333"),
                            HomeTeamId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MatchDateUtc = new DateTime(2026, 3, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        });
                });

            modelBuilder.Entity("MundialCorporativo.Domain.Entities.MatchScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MatchScores", (string)null);
                });

            modelBuilder.Entity("MundialCorporativo.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("GoalsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GoalsScored")
                        .HasColumnType("integer");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000001"),
                            FullName = "Tigres Tech Jugador 1",
                            GoalsAgainst = 0,
                            GoalsScored = 2,
                            JerseyNumber = 1,
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000002"),
                            FullName = "Tigres Tech Jugador 2",
                            GoalsAgainst = 0,
                            GoalsScored = 1,
                            JerseyNumber = 2,
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000003"),
                            FullName = "Tigres Tech Jugador 3",
                            GoalsAgainst = 0,
                            GoalsScored = 1,
                            JerseyNumber = 3,
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000004"),
                            FullName = "Tigres Tech Jugador 4",
                            GoalsAgainst = 0,
                            GoalsScored = 1,
                            JerseyNumber = 4,
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000005"),
                            FullName = "Tigres Tech Jugador 5",
                            GoalsAgainst = 0,
                            GoalsScored = 1,
                            JerseyNumber = 5,
                            TeamId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000006"),
                            FullName = "Leones Data Jugador 1",
                            GoalsAgainst = 0,
                            GoalsScored = 1,
                            JerseyNumber = 1,
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000007"),
                            FullName = "Leones Data Jugador 2",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 2,
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000008"),
                            FullName = "Leones Data Jugador 3",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 3,
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000009"),
                            FullName = "Leones Data Jugador 4",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 4,
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000010"),
                            FullName = "Leones Data Jugador 5",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 5,
                            TeamId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000011"),
                            FullName = "Halcones DevOps Jugador 1",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 1,
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000012"),
                            FullName = "Halcones DevOps Jugador 2",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 2,
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000013"),
                            FullName = "Halcones DevOps Jugador 3",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 3,
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000014"),
                            FullName = "Halcones DevOps Jugador 4",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 4,
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000015"),
                            FullName = "Halcones DevOps Jugador 5",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 5,
                            TeamId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000016"),
                            FullName = "Toros Cloud Jugador 1",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 1,
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000017"),
                            FullName = "Toros Cloud Jugador 2",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 2,
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000018"),
                            FullName = "Toros Cloud Jugador 3",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 3,
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000019"),
                            FullName = "Toros Cloud Jugador 4",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 4,
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-000000000020"),
                            FullName = "Toros Cloud Jugador 5",
                            GoalsAgainst = 0,
                            GoalsScored = 0,
                            JerseyNumber = 5,
                            TeamId = new Guid("44444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("MundialCorporativo.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Tigres Tech"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Leones Data"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Halcones DevOps"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Toros Cloud"
                        });
                });

            modelBuilder.Entity("MundialCorporativo.Infrastructure.Persistence.Entities.DomainEventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("DomainEventLogs", (string)null);
                });

            modelBuilder.Entity("MundialCorporativo.Infrastructure.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Path", "Method")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("MundialCorporativo.Domain.Entities.Match", b =>
                {
                    b.HasOne("MundialCorporativo.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MundialCorporativo.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MundialCorporativo.Domain.Entities.MatchScore", b =>
                {
                    b.HasOne("MundialCorporativo.Domain.Entities.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MundialCorporativo.Domain.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MundialCorporativo.Domain.Entities.Player", b =>
                {
                    b.HasOne("MundialCorporativo.Domain.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
